# Generated by Django 2.1 on 2018-08-23 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular photo', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, help_text='Add a photo description', max_length=160)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner'],
                'permissions': (('can_edit_photo', 'Change photo details'),),
            },
        ),
    ]
