# Generated by Django 2.1 on 2018-08-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoinstance',
            options={'ordering': ['owner']},
        ),
    ]
