# Generated by Django 2.1 on 2018-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180823_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoinstance',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
