# Generated by Django 2.1 on 2018-08-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photoinstance_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoinstance',
            name='description',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
