# Generated by Django 2.1 on 2018-08-30 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0007_auto_20180830_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoInstance',
            new_name='Photo',
        ),
    ]
