# Generated by Django 2.1 on 2018-09-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20180830_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
