# Generated by Django 2.1 on 2018-09-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_photo_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='path',
            field=models.CharField(blank=True, default='photos/%Y/%m/%d', max_length=160),
        ),
    ]
