# Generated by Django 2.1 on 2018-09-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_photo_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='path',
        ),
    ]
