# Generated by Django 2.1 on 2018-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_remove_photo_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['owner', 'uploaded']},
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
