# Generated by Django 2.1 on 2018-08-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20180829_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoinstance',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
