# Generated by Django 2.1 on 2018-08-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photoinstance_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoinstance',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
