# Generated by Django 2.1 on 2018-09-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_photo_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
    ]
